In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

In [38]:
A = np.array([[3,4,2,5],
             [4,1,2,3],
             [12,42,32,4],
            [2,3,4,7]])
B = np.array([[13,9,7,15],
             [8,7,4,6],
             [6,4,0,3],
              [4,2,5,1]])
C = np.array([2,1,3,4])

In [28]:
A@B

array([[103,  73,  62,  80],
       [ 84,  57,  47,  75],
       [700, 538, 272, 532],
       [102,  69,  61,  67]])

In [29]:
5+3*B

array([[44, 32, 26, 50],
       [29, 26, 17, 23],
       [23, 17,  5, 14],
       [17, 11, 20,  8]])

In [30]:
5+3*A

array([[ 14,  17,  11,  20],
       [ 17,   8,  11,  14],
       [ 41, 131, 101,  17],
       [ 11,  14,  17,  26]])

In [31]:
I4 = np.eye(4)

In [32]:
I4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
B.shape

(4, 4)

In [34]:
A.shape

(4, 4)

In [35]:
B@I4

array([[13.,  9.,  7., 15.],
       [ 8.,  7.,  4.,  6.],
       [ 6.,  4.,  0.,  3.],
       [ 4.,  2.,  5.,  1.]])

In [36]:
B

array([[13,  9,  7, 15],
       [ 8,  7,  4,  6],
       [ 6,  4,  0,  3],
       [ 4,  2,  5,  1]])

In [37]:
invA = np.linalg.inv(A)

In [39]:
C

array([2, 1, 3, 4])

In [40]:
C.shape

(4,)

In [41]:
invA

array([[ 0.06445672,  0.28913444, -0.00092081, -0.1694291 ],
       [ 0.29097606, -0.18047882,  0.01012891, -0.13627993],
       [-0.41804788,  0.13904236,  0.02025783,  0.22744015],
       [ 0.09576427, -0.08471455, -0.01565378,  0.11970534]])

In [42]:
P = A@B

In [43]:
P

array([[103,  73,  62,  80],
       [ 84,  57,  47,  75],
       [700, 538, 272, 532],
       [102,  69,  61,  67]])

In [45]:
np.allclose(P,np.eye(4))

False

In [46]:
np.round(invA)

array([[ 0.,  0., -0., -0.],
       [ 0., -0.,  0., -0.],
       [-0.,  0.,  0.,  0.],
       [ 0., -0., -0.,  0.]])

In [47]:
np.round(invA) + 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])